indexes:
  list:
    searchd:
      - video
    indexer:
      - video

constants:
  extends: default

searchd:
  extends: default
  options:
    listen:
      - '0.0.0.0:3312'
      - '0.0.0.0:9306:mysql41'
    binlog_path: '/var/db/sphinxsearch/log'
    log: '/var/db/sphinxsearch/log/searchd.log'
    query_log: '/var/db/sphinxsearch/log/query.log'
    pid_file: '/var/db/sphinxsearch/log/searchd.pid'