indexes:
  list:
    searchd:
      - video
    indexer:
      - video

constants:
  @include: default/constant.yaml

searchd:
  options:
    @include: default/searchd.options.yaml
    listen:
      - '0.0.0.0:3313'
      - '0.0.0.0:9307:mysql41'
    binlog_path: '{SPHINX_DATA_PATH}/log'
    log: '{SPHINX_DATA_PATH}/log/searchd.log'
    query_log: '{SPHINX_DATA_PATH}/log/query.log'
    pid_file: '{SPHINX_DATA_PATH}/log/searchd.pid'